# Generated by Django 3.2.19 on 2023-06-22 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('car_brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('Other', 'Other')], max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_color', models.CharField(max_length=255)),
                ('car_number', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255)),
                ('offer_description', models.TextField()),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_expiry', models.DateField()),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicerequest')),
                ('subscription_option', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.subscriptionoption')),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='subscription_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.subscriptionoption'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
