# Generated by Django 3.2.19 on 2023-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscriptionoption_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoption',
            name='count',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
