# Generated by Django 3.2.19 on 2023-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('success', 'success')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='car_brand',
            field=models.CharField(blank=True, choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='car_color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='car_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='car_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
