# Generated by Django 3.2.19 on 2023-06-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicerequest_request_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
